name: Pokedex-SwiftUI
options:
  deploymentTarget:
    iOS: 13.0
packages:
    Alamofire:
      url: https://github.com/Alamofire/Alamofire.git
      version: 5.2.2
    Nuke:
      url: https://github.com/kean/Nuke.git
      version: 9.1.2
    SwiftUIX:
      url: https://github.com/SwiftUIX/SwiftUIX.git
      version: 0.0.8
settings:
  DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC: YES #Read: https://forums.swift.org/t/adding-a-package-to-two-targets-in-one-projects-results-in-an-error/35007
fileGroups:
targets:
  Pokedex-SwiftUI:
    type: application
    platform: iOS
    sources: [Pokedex-SwiftUI]
    settings:
      PRODUCT_NAME: Pokedex(SwiftUI)
      CURRENT_PROJECT_VERSION: 1
      PRODUCT_BUNDLE_IDENTIFIER: pokedex-swiftui
      CODE_SIGN_STYLE: Automatic
    dependencies:
    - target: DataStore
    - target: Domain
    - target: Presentation
    postbuildScripts:
          - script: |
              if which mint >/dev/null; then
                mint run swiftlint swiftlint autocorrect --format
                mint run swiftlint swiftlint
              else
                echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
              fi
            name: Run SwiftLint
  DataStore:
    type: framework
    platform: iOS
    sources: [DataStore]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.DataStore
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: Alamofire
      - package: Nuke
  Presentation:
    type: framework
    platform: iOS
    sources: [Presentation]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.Presentation
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: Domain
      - package: Nuke
      - package: SwiftUIX
  Domain:
    type: framework
    platform: iOS
    sources: [Domain]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.Domain
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: DataStore
  PokedexTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PokedexTests
    settings:
      base:
        INFOPLIST_FILE: PokedexTests/Info.plist
    dependencies:
      - target: Pokedex-SwiftUI
